openapi: 3.0.0
info:
  title: Example Service
  version: 1.0.0

paths:
  /api/v1/messages:
    get:
      parameters:
        - $ref: "#/components/parameters/UserAgent"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/SenderId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponseBody'

components:
  parameters:
    UserAgent:
      in: header
      name: User-Agent
      description: >
        The User-Agent request header is a characteristic string that lets
        servers and network peers identify the application, operating system,
        vendor, and/or version of the requesting user agent.
      required: true
      schema:
        type: string

    Limit:
      in: query
      name: limit
      description: Request at max this number of messages.
      required: true
      schema:
        type: integer

    SenderId:
      in: query
      name: sender_id
      description: Requests messages only from this sender.
      required: false
      schema:
        type: string

  schemas:
    MessagesResponseBody:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      additionalProperties: false

    Message:
      type: object
      required:
        - id
        - sender_id
        - text
      properties:
        id:
          type: string
        sender_id:
          type: string
        text:
          type: string
      additionalProperties: false
